# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idP', models.IntegerField()),
                ('titulo', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('distancia', models.FloatField()),
                ('valorNutricional', models.FloatField()),
                ('imagen', models.CharField(max_length=300)),
                ('valoracion', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Serie',
        ),
    ]
